# Generated by Django 2.0.4 on 2018-07-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_auto_20180629_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_alum',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_mentor',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_student',
        ),
        migrations.AddField(
            model_name='profile',
            name='grad_year',
            field=models.CharField(blank=True, choices=[(2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='school',
            field=models.CharField(blank=True, choices=[('AAHS', 'Allied Health'), ('AIT', 'Academy for Information Technology'), ('APA', 'Academy for Performing Arts'), ('MHS', 'Magnet High School'), ('UCT', 'UCTech')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'male'), ('F', 'female'), ('NB', 'non-binary/other'), ('X', 'prefer not to answer')], max_length=10, null=True),
        ),
    ]
