# Generated by Django 2.0.4 on 2018-07-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_auto_20180701_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='grad_year',
            field=models.CharField(blank=True, choices=[('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023')], max_length=4, null=True),
        ),
    ]
