# Generated by Django 2.0.4 on 2018-07-01 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_auto_20180701_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_active',
        ),
    ]
