# Generated by Django 2.0.4 on 2018-08-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_person_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='middle',
            field=models.CharField(blank=True, default='!!!', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='preferred',
            field=models.CharField(blank=True, default='!!!', max_length=255),
            preserve_default=False,
        ),
    ]
