# Generated by Django 2.0.4 on 2018-07-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=40)),
                ('last', models.CharField(max_length=40)),
                ('current_name', models.CharField(blank=True, max_length=50, null=True)),
                ('grad_year', models.CharField(blank=True, choices=[(2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], max_length=4, null=True)),
                ('school', models.CharField(blank=True, choices=[('aahs', 'Allied Health'), ('ait', 'Academy for Information Technology'), ('apa', 'Academy for Performing Arts'), ('mhs', 'Magnet High School'), ('uct', 'UCTech')], max_length=4, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
